name: predictive-maintenance-ifsul
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - conda
  - cython=0.29.2=py36hfc679d8_0
  - pip=18.1=py36_1000
  - numpy=1.15.4=py36_blas_openblashb06ca3d_0
  - pip:
    - autopep8==1.3.5
    - catboost==0.11.1
    - dash==1.9.0
    - dash-bootstrap-components==0.9.1
    - dash-core-components==1.8.0
    - dash-html-components==1.0.2
    - dash-renderer==1.2.4
    - dash-table==4.6.0
    - plotly==4.5.1
    - datetime==4.3
    - flake8==3.6.0
    - psycopg2-binary==2.7.6.1
    - pytest==4.0.1
    - python-dotenv==0.9.1
    - statsmodels==0.9.0
    - celery==4.4.2
    - scikit-learn==0.20.1
    - matplotlib==2.2.3
    - gunicorn
    - setuptools
    - pandas_datareader
    - WTForms
    - SQLAlchemy
    - Flask
    - Flask-Login
    - Flask-Script
    - Flask-SQLAlchemy
    - Flask-WTF
    - Flask-BCrypt
    - Flask-Bootstrap
    - wheel
    - email_validator==1.1.3
    - python-dateutil
    - torch
    - requests
    - pandas==0.22.0
    - seaborn==0.9.0    
    - awscli==1.16.108
    - -e .
