name: predictive-maintenance
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - conda=4.5.12=py36_1000
  - cython=0.29.2=py36hfc679d8_0
  - fbprophet=0.3.post2=py36_0
  - pip=18.1=py36_1000
  - pystan=2.17.1.0=py36hf8a1672_2
  - xgboost=0.81=py36hfc679d8_0
  - numpy=1.15.4=py36_blas_openblashb06ca3d_0
  - pip:
    - autopep8==1.3.5
    - catboost==0.11.1
    - datetime==4.3
    - flake8==3.6.0
    - prophet==0.1.1
    - psycopg2-binary==2.7.6.1
    - pytest==4.0.1
    - python-dotenv==0.9.1
    - statsmodels==0.9.0
    - torch==0.4.1
    - scikit-learn==0.20.1
    - tensorflow==1.12.0
    - Keras==2.2.4
    - matplotlib==2.2.3
    - pandas==0.22.0
    - seaborn==0.9.0    
    - setuptools==40.6.3
    - wheel==0.32.3
    - awscli==1.16.108
    - python-dateutil==2.7.5
    - -e .
